### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by peterpramb** [PeerJ/pynagioscheck#1]
Unfortunately the original repository disappeared, and now that Python 2 dies a number of fixes are necessary.

Is this package still actively maintained? Is somebody accepting pull requests?

**Comment by peterpramb** [comment]
@saj Maybe the original author can provide some input, whether this project is still maintained (somewhere)?

**Comment by saj** [comment]
I am surprised to see this little thing still kicking around after so long.

No, I am not aware of any actively maintained forks.  It has been many years since I last worked with Nagios, and all of my old colleagues -- some of whom may have contributed to this library -- have likewise moved on to other endeavours.  I do not personally know of anyone currently using this library in production.

**Comment by peterpramb** [comment]
@saj Well, things often live longer than expected. :wink:

I'm using it in production with Icinga, and some public plugins depend on it as well. Personally, I like it: it provides (nearly) everything needed and is self-contained; it just needs some small adaptions.

Thanks for feedback, then I'll stick to my fork.
